18 490
NC_003683. ---------- CTTACCTGGG TTCCC----- --------TG GCAGC-GCTG
NC_021720. ---------- CTTACCTGTC GTCGT----- --------CG ACGAA-GGCT
NC_003553. ---------- --CACCTGGC GACTC----- GTCGTCGACG AAGGG-TCCT
NC_003777. ---------- --CACCTGGT GACTC----- GTCGTCGACG AAGGG-TCCT
NC_003612. ---------- -----GAATG AGCCT----- --CGTCGTCG ACGAA-----
NC_004359. ---------- -----GAGTG AGCCTCGTCG TCGACGAAGG GGTGC-ACTC
NC_014129. ---------- -----CAGTT ATTTC----- -----CACCG GGTAGTAGCC
NC_027432. ---------- CGCTTCAGGG ATCCC----- --------CG GGGAA-ACCT
NC_003613. ---------- CGCTTCAGGG ATCCC----- --------CG GGGAA-ACCT
NC_011590. ---------- CTGTTCAGGG ATCCC----- --------CG GGGAA-ACCT
NC_003538. AGCGCAAGAG CGGTCTCAGG AGCCC----- --------CG GGGCA-ACTC
NC_001558. ---------- CGCTTCAGGG ATCCC----- --------CG GGGAA-ACCT
NC_003637. ---------- CGCTTCAGGG ATCCC----- --------CG GGGAA-ACCT
NC_002030. ---------- CGCTTCAGGG ATCCC----- --------CG GGGAA-ACCT
NC_000885. ---------- CGCTTCAGGG ATCCC----- --------CG GGGAA-ACCT
NC_002015. ---------- TCCTTCAGGG ATCCC----- --------CG GGGAA-ACCT
NC_001553. ---------- TCCTTCAGGG ATCCC----- --------CG GGGAA-ACCT
NC_001464. ---------- TCCTTCAGGG ATCCC----- --------CG GGGAA-ACCT

CAAC----GG AATCCAGGGC GTTGGCCCCG AT-------- -----GGAGT TTCCGATG--
GGTAAGC-AG AGCCCGTTGA AG-CTCCCCG TG--ACGAGC GTCGTCGGAT GGCCTCCGAG
CAGC----AG AGCACCGGCA GG-AGGCGCT ATGCAGGAAC GCTAGGGGTC CTCC------
CAGC----AG AGCACCGGCA GG----CGCG GCGAAGCGGA GAACGCTAGC CGTCCTCC--
GGGG----TG CATTCCGAAG AGCTGGCCTG GC-------- ---GTCGTCC GGCTCCC---
CAAAGCTCCG AACTGGCGTC GTCCGGCTCT CC-------- ---TCGGAGC CTCGC-----
GAAG----CG ACAGCGCAAA GG-GGGCG-- ---------- ---AGGGGTG GTCCTGCG--
GGAG----CG ACCTCGGCAG GA-AGGCTTG GCGGTAGGTG AAGAAGGAGC GAGCGCCGTA
GGAG----CG AACTCGGCAA GG-AGGCCTG GC--GGTAGG TGCGCGGAGT CGACCGCG--
GAA-----CA GATCGGGCGG AG-AAGCGCC GT-------- ---GCGGGTC CGTCTTC---
AGAC----CG AGC-----GG GG-TCTCGTG GT-------- ---CGAGGGC GTTGCCC---
GGAG----CG AACTGGCGAA GG-AGTCGCG GC-------- ---TGGGGAG TCTCC-C---
GGAG----CG AACTGGCAAA GG-AGTCGCG GC-------- ---TGGGGAG TCTCCTC---
GGAG----CG AACTGGCAAA AA-AGG-ACG GT-------- ---GGGGAGT GCCCAGC---
GGAG----CG AACTGGCAAA A----G-GCG GC-------- ---AGGGAGC TTGTGGA---
GGAG----GA AGTCCGACGA GA---TCGCG GT-------- ----TGGGGC TTAGGACCCC
GGAG----GA AGTCGAGGTC GG-GGGCT-- ---------- ---TCGGATC ATTCC-----
GGAG----GA AGTCGAGGTC GGGGGGGACA GC-------- ---------- -TGCTTCGGT

---AGCACCG GTGAGAAGAA ACTG---TCT CGCAGAATAG AAGTCTCTTC TTGTTTGCTT
ACGAGCGATG GACAGTGGAG CTCT------ ---------- ----GCTCTC ACCAGTCGCG
---AGCGGAG GACTGAAGAA ACTC---C-- ---------- ----GGTTTC TTCTTTCACT
---AGTGGAG AACTGGAAAA GCTC---C-- ---------- --GGCTTTTC CTTTTTTCTG
---TCGACCG CACCGGAGCG CT-------- ------AGAA AAG-GTCCTC GGACTTTCTT
---TGCTCTG GGCGGAAGA- ---------- ---------- ----GTCTTC TGACTTTTCT
---GGCGCGA GGAAGGA--- -------CAC CCGAAGAAAG GAAGGGTGAA AACCCTGTTT
ACGACCTGAG AACAGGA--- ---------- -----GAAAC AGGAGCTCGA CTCCTTCCTT
------TAAA GACCGGAGAA CTCCTCGCGG CGGAAGAAAC AGGAGCTCGA CTCCTTCCTT
---TG----- -ACAGGAGTA ATCC---C-C GCT--GAAAC AGG-GTTTTC ACCCTTCCTT
---TGTTC-A GACAGGAGTA ATCC---C-A GCT--GAAAC AGG-GTTTTC ACCCTTCCTT
---AG----- -ACAGGAGTA ATCC---C-C GCT--GAAAC AGG-GTTTTC ACCCTTCCTT
---AG----- -ACAGGAGTA ATCC---C-C GCT--GAAAC AGG-GTTTTC ACCCTTCCTT
---GGC-CG- -ACAGGAGTA ATTC---C-C GCC--GAAAC AGG-GTTTTC ACCCTTCCTT
---AGG-CGA AACAGGAGTA ATCC---CGT GTA--GAAAC AGG-GTTTTC ACCCTTCCTT
ACTCCTGCGA GACAGGAGTA ATCC------ -----TAAAC AGG-GTTTTC ACCCTTCCTT
---TGGTTGA GACAGGAGTA ATCC---C-A GCT--GAAAC AGG-GTTTTC ACCCTTCCTT
CGCCGCGGAT CACTGGCGT- -------CCA GCGGAGAAAC AGGAGCTCGT CTCCTTCCTT

T--------- ---------G AGACTTCTT- -CTCC----- --ACAGGGCT CTTCGGCTCT
T--------- ---------G TTGACTCTC- -GCGC----- ---------- CTACCCGAAC
CTGTAGCT-- ---------G GAATCCCTG- -TTGC----- ---------- ----GCTTGC
TAACTG---- ---------G AACGCGCTG- -TTGC----- ---------- ----GCTCGC
CTATCTCC-- ---------G AAGCCGGTT- -TGAG----- ---------- ----------
AGCCTATTC- ---------A GCATTGCGC- -TCTTGAGGC CCGGCG---- -AAACGCGGT
CGGCG----- ---------G GAATTACTC- -C-----TGT CGGCCGCTGG GCACTCCCCA
T--CTTCTCT CATCGGGCAG GTGCCGCTT- -CCCT----- ---------- ----CCACCC
T--CTGTCGC CCGCA----G GACTCACCTG GCAGCGGCGT CTTC------ -TCCGCACCC
T--CTTCG-- ---------G GTTTC-CTT- -CCTC--AGT CGACCGGACC GCGTCGGCCT
T--CTTCT-- ---------G GTTTC-CTT- -CCTCTGCTT CAGCGG---- --------CC
T--CTTCG-- ---------G GTTTC-CTT- -CCTC--TGC GGTCGA---- -CACCCTCGC
T--CTTCG-- ---------G GTTTC-CTT- -CCTC--TGT GGTCGA---- -CACCCTCGC
T--CTTCG-- ---------G GTGTC-CTT- -CCTCG-CGC CCGCAG---- -GACCACCCC
T--CTTCTGC ---------G GTTTC-CTT- -CCTT--TGC GCGCCA---- -CTCGACCCC
T--------- ---------A GTTTC-CTT- -CCTC----T CCTGGAGAGG TCTTCTGCCC
T--CTTCT-- ---------G GTTTC-CTT- -CCTC----T CGCCGGAAGG TCTTCGGCCC
TCGCTGCT-- ---------G GCTCCACAT- -CCGA-TCGT CGCTGAAGCG CCTCGCCCCC

TCGCGGG-TA CCCAGC---- ----AACCTG CTCCCACGCG GCGATTGCAA AGGACC----
ACGGCTG-TT CTGAGGGCGC TGAGGGCCGA GCTTCCCGCC GCTAGTCGAG CGGACC----
TGGCGAA-AC CTGCAG-GGA AGCTAGCTGG GTCCCGCTAG TCGAGCGGAC TCGTCCCAG-
TAGCCAG-AC CTGCAG-GGA AGCTAGCTGG GTCCCGCTAG TCGAGCGGAC TCGTCCCAG-
--GCCCGGCG AAACGCGGGC CTGTCTCCTA AGATGCCTCC GCTAGTCGAG CGGACTTGGC
TCGTCTG--- ---------- ------CTGA GGATGCCTCC GCTAGTCGAG CGGACTTGGT
CCGTCCTTTT TTGC---CAG TTCGCTCCAG GTTTCCC--- -----CGGGG ATCCCTGAAG
TCGCCGG-TC TTCTGC-GCT GGCGCTCTGG CTACTAC--- -CCGGTGGAT ACAACTGAC-
CCGCCCGCTT CCGCGCTGG- -TCGCTCTGG CTACTAC--- -CCGGTGGAT ACAACTGTA-
TCTCGCG-C- --------AC TTCTGTTCGG AGACTAC--- -CCGGTGGAT ACAACTGAC-
TCGCCCG-GA ACCTCT-TGA CCAGCGCAGG TGCTGACGCG ACCGGTGGCA TC-ACCGAGT
CCGCTTC-TC TTGCGC-TG- -TCGCTTCGG AGACTAC--- -CCGGTGGAA ACAACTGAA-
CCGCCTC-TC -TGCGC-TG- -TCGCTTCGG ATACTAC--- -CCGGTGGAA ACAACTGAA-
TCGCCCC-CT TTGCGC-TG- -TCGCTTCGG CTACTAC--- -CCGGTGGAA ACAACTGAA-
TCGCCCC-C- TTGCGC-TG- -TCGCTTCGG CAACTAC--- -CCGGTGGAA ACAACTGAA-
TAGCCCG-GT CTTCGA--AG CTTCCTTTGG CTACTAC--- -CCGGTGGAA ACAACTGAA-
TCGCCCG--- -----G-AGC TTCTCTCTGG AGACTAC--- -CCGGTGGAA ACAACTGAA-
TCGCCCG--- ------GAGC TTCTCTCTGG ATACTAC--- -CCGGTGGAA ACAACTGAA-

------CGGT TCGCTCTCCT TTTCTTATTT ACCTG-CTTC AGACCGACCG CCCCGGGGAG
---------- ----ACTGGT AGTTCCCCCG ACCTG-CCTA TTTTTGTAGC CTAGGGAGAG
------CGGT CCCAACCAGT TTTCTTT--- ATCCT-ATTT TTCCTGCGGG CGCCCGGTCG
------CGGT CCCAACCAGT TTTATTT--- ATCCTATTTT TCCCTGCGAG CGCCCGGTCG
CTCTTCCGCC -CGAGGACCT TTTCTTTCTA ATCTT-GCTT GTTCCAACGA GCCCCGCGAG
CTCTTCCGCC CAAAGCCCTT TTTCTTTC-- AACTGAGCTT GTTCCAACGC GCCCCGCGAG
CGCTCC---T CCGAGCCGCC TTCTTTTT-- -TCTT-TTCT GCTCAGGAGG T---CAGGTG
-GCTTGTACT CCGCCCTGCC TTTTTCT--- ------ACTT CTTCGCTGGA GCGGCGAGGG
-GCTTGAAGC CCGCCCGCCC TTTTTCTTCA TTCTTCTGCT GCGC----GG C----GAGGG
---------- -AGAGGTGCT TTTTCTTCC- ACCCT-GCTT CTAC-CGACG CGGCCGGGAG
TGCTCGAGCC TCAACCTCCT TTTTCTCT-- ATCTTAGCTT GGTCTCCGGG C----GAGGG
-GCTCCCAAG ---CGCCGCT TTTTCTCT-- ATCTT-GCTG GCTC-CGGGG C----GAGGG
-GCTCCCGAG ---AACCGCT TTTTCTCT-- ATCTT-GCTG GCGC-AGGGG C----GAGGG
-GCTCCCGAG ---AACCGCT TTTTCTCT-- ATCTT-ACTT GCTT-CGGGG C----GAGGG
-GCTCCCGAG ---AACCGCT TTTTCTCT-- ATCTT-GCTG CTAC-CGGGG C----GAGGG
-GCTTC---- ----AACGCC TTTTTTTCCA ACCTT--CTT TAGCACCGGG C--CAGGGAG
-GCTTCCACT TCCACGCTCT TTTTCTCT-- ATCTT-TGTT GCTCTCCGGG C----GAGGG
-GCTTCAACC CCAAACCGCT TTTCTTAT-- ATCTT-CACT GCTCTCCGGG C----GAGGG

TG---AATCA CTGG--AACC GCGAGAAAAA GG----ATCC TCGGATCATT TTCCTTGTGG
TGGAGTCACC AGGGTAAAAC AC----GATT GGTGTTTTCC CCGGAGAAAA CTCCGTGTGG
TGGTTA--CC CTGG--AGCT CC-CTGTTTG GA----GGCC CTGGGCACCA A--CTAGAGG
TGGATG--CC TAGG--ATTC CC-GAGTTTG GG----TGCC CTGGGCTCCA A--CTAGTGG
TGGA-ATCCC CGGA--ACCC CTGCGAAAAA GG----GTCC TCGGATCATT TTCCTTGTGG
TGCAAT--CC CCGG--AACC CC-TGCAAAG AG----GTCC TCGGATCACT TT-CCTGTGG
TG---AACCA CAGG--AACC AC--GAGTTT AG----TTCC GAGGGAACCA A--CTGCGGG
TG-------- ---------- ---------- GG----CTTC TAAGGAAACC ---CTTGTGG
TG-------- ---------- ---------- ------GGCT TCTAAAGGAA ACCCTCGTGG
TGAAGCTACC CGGG--ACCC ------GAGA GG----ATCT CCGGATTCTT ---CTAAGGG
TGTTTAGCCC TTGG--AACC GC----AGTA GG----TTCC TCGGAA--CT AAACTCGTGG
TGGAAAACCC TGGA--ACCC TT-CGAAAAG GG----TCCC TCGGGATCTT TTCCTTGTGG
TGGAAAGCCC TGGA--ACCC GC-TG-GATG GG----TCCC TCGGGATCTT TTCCTTGTGG
TGTTTAGCCC TTGG--AACC GC----AGTT GG----TTCC TCGGAA--CT AAACTCGTGG
TGTTTAGCCC TTGG--AACC GC----AGTT GG----TTCC TCGGAA--CT AAACTCGTGG
TT---AGCCC TTGG--AACC TT--AGTATT GT----TCCC TCGGGACTTA ---CTTGTGG
TG-AAAGCCC GTGG--AACC CT----GAAT GG----TCCC TCGGGATCTT T--CGTGAGG
TG-AAAGCCC TCGG--AACC CT--AGATTG GG----TCCC TCGGGATCTT T--CTTGAGG

TTCCTGTGG- TACACCTCCG AAGGCGCGCT CGGCGAGAAG AGAGTAAATA GAAGAGAGAG
TTCCTGTGT- GGCACC-CCT CCCG----CT ACGGGCTTTA AAAAGAAAGC AGGGAAGGGT
TTCCTGTGG- TACTCA-CCG AAGG----CC GCGAACGTAG GAAAGAAAAA GATAGAAAAG
TTCCTATGGT TACACA-CCG AAGG----CC GCGTAGCTTG GAAAGAAAAG ATATAAAAGC
TTCCTGTGGT TACACC-TCG GAAGGCCTCC GCGGACCTGC AGAGAAAAGA AGAAGG----
TTCCTGTGGT TACACC-TCG GAAGGCCGCC GCGGACCTGC AAAGAAGAAG ATAGGG----
TTCCCAGGGC TAAACACCCT CG------CC CCGAAGCAAG TAAGATAGAG AAAAAGCGGT
TTCCTATGGT TGCACC-CCT GAC-----CT GCTACCTGCA AAAGAAAAAA GATGGGCAGG
TTCCAATGG- TGCACC-CCT GAC-----CT GCAATGCAAA AAGAAAAAAA GATGGGGCGG
TGCCTGTGG- TGCCTC-C-- ---C----CC GAAGCCCGCT TAGGGAAAAA GAAAGG----
TTCCTGTGG- TACACA-CCT GACC----CT GCAGCCATGC AAAAGAAAAA AGAACG----
TTCCTGTGG- TACACA-CCT GA-C----CT CCTGACCAGA AAAGAAAAAA GAATTGCGGC
TTCCTGTGG- TTCACA-CCT GA-C----CT CCAGCCCAGG AAAGAAAAAA GAAAGGCGGC
TTCCTGTGG- TTCACA-CCT GA-C----CT CCTGAGCAGA AAAGAAAAAA GA-AGGCGGC
TTCCTGTGG- TTCACA-CCT GA-C----CT CCTGTGCAGA AAAGAAAAAA GATAGGCGGC
TTCCTGTGG- TGCACT-CCT GACC----CT GCTGCTATAG CAAAGAAAAA GAAATGAGGC
TTCCTGTGG- TGCTCA-CCT GACC----CT GCAGGCATCA AGAAAAAAGA TAGGAGCGGG
TTCCTGTGG- TGCTCA-CCT GACC----CT GCAGGCAGGA AAAGAAAAAA GAGGCGGCGG

---------- ----------
A--------- ----------
CTGGGTAAGA CT--------
TGGGTAAGAC T---------
--GCCCAGAG GG--------
----GCAGAG GGG-------
TCTCGGGAGC TT--------
CGAGCACAA- ----------
CGGCTACAA- ----------
-----GGAAG CAAGCATCTC
-----GGAGG GAG-------
-----CAAAG GAG-------
----TCGGAG GAG-------
----TCGGAG GAG-------
----TCGGAG GAG-------
------GAAG AAG-------
AAGGAAGAAG ----------
----GGGAAG AAG-------
